travis:
  secure:
    BINSTAR_TOKEN: Ug2X4qu0SZU0YxUyRbCvqlZKDWQwEJa1fGur0Bu1Aacvqc2E5YJ5HsZu0IQhPOhPN7KSpemI3yQTb/1GfrJ0h6XiGolKPIGWpCUa44e9y1zKCOPd9VE3BCBinMdmEnfc1O2rpxRvuN3eepPalxI+veehnmdcOT/rDYOb67juo9tNvgNgVvTH0nH3tcb5TgNxIZnSkEOngaLV98g/xfXCW3jlXvZDxwYXLxIBhPVMMErHWugSNCIPsM9z80rATtKcd+TV6+h7qeaCLDj1qA+GwFtUmsS5/Maylse6Rm9rYKr0wmyj4sNq9kwHoonUUtCElrBJp7TNpIvDmB99maE7l9DiztJj1ZShYAW4tV+/8rUo99oM0H/PNClt0d66TWaRhekmSVzCmo2ZGZi3yv9Jhn1cYA8Fx7s7ISSYntiOfGZ2T30mKJRF2M5wc296N86EoO2Req1mVLeWIqu3TZHN8LzIKf0nPTrzmcKQH1n/Dllu/Ier1ELS7i1MUFe3uVu+du/EY2krEHSefFT6M9Mwtk4r7A6jqDJVRUotvHEz25m9IlJKf1RKfzo1D+ki0Qs862ojp3u9Ebnth8YfedPAL/lPtQb7bED6EY/00z0bBqutzfhZ+sLp2T0wr/dSGhiu1y9XlxcK2j3meXwbGpKsixoge5ySUBxhpHMXXfEoKhs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
