travis:
  secure:
    BINSTAR_TOKEN: nzHXwiu15bOYRynExLsSPLgnBZl64SjvQVtMA6dcewm/lSq35Q0MkuLGvVXg2//BiXVVqZf/vucFm0x7aF3/oA47ppzXBSrRrZu7cZ0DFGSCzMa/ZD4+uMMs4fruNbczKLeeZAmhuiai0YLLwFjMyZuplswhsKeUjQZIS+Bj6sv8Ia1MBnASVaudOCQODc5EHAwBAJyGCxR4FJ9Oj+7TOilqmGqF63dysggBFhtnJEIjD302HTwnC3dC2Yh4Px4UlH+chPsJZ1rWFowGY5jEH1NDqcn8qusUQ3PdUz+sJkjKQi/8qCBofp5nM4KoasLPL2YxeHFJhX4GAWL2TUB6hBE9Y+hIFkCCGAJOEmh1XPUrZtIJApiRHVx5DuIN6K4ZZg3Y0A588+HTDGUOKYcM4QHxpKyDbICtI8++bA7dVBIV7aGfFLnpPN2avB090P0djzSbotkC+urpcL4dKRX7EenncNuC/jnkEOVdZpaZTDSRuaDKFdTJijRjBPu86EZKfb2XxzllFOHF4MdZkr6qaEkIww+zeYDxtwgSId5MzKJcRFkGXLxXR6K9jQaUsFEkWmQCuDP53CR1534t5FxaVDaXs3045DBXeoybYeHdBR4bDhSak4Yp0qMpHjreelOa7kos5gZtRT8GEwreJNXgQ3yjx8mGGbvx8o5tnw3A970=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
